# Generated by Django 4.1.3 on 2022-11-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.productbatch'),
        ),
        migrations.AddField(
            model_name='cart',
            name='totalprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
