# Generated by Django 3.1.2 on 2020-11-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_order_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
