# Generated by Django 3.1.2 on 2020-11-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_auto_20201122_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
