# Generated by Django 3.1.2 on 2020-11-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_auto_20201122_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
