# Generated by Django 3.1.2 on 2020-12-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
