# Generated by Django 4.1.3 on 2022-11-11 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_alter_address_id_alter_cart_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
